routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {
    Route::get('', 'AppController@app')->name('app');
    Route::get('archived', 'AppController@archived')->name('app.archived');
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::post('profile', 'ProfileController@update')->name('profile:update');

    Route::group(['prefix' => 'ajax'], function () {
        Route::get('liquids/random-name', 'LiquidController@randomName');

        Route::resource('flavours', 'FlavourController', [
            'only' => ['index', 'show', 'store']
        ]);

        Route::resource('liquids', 'LiquidController', [
            'only' => ['index', 'show', 'store', 'update', 'destroy']
        ]);
        Route::post('liquids/{liquid}/new-version', 'LiquidController@newVersion');
        Route::post('liquids/{liquid}/unarchive', 'LiquidController@unarchive');
        Route::get('archived-liquids', 'LiquidController@archived');

        Route::get('liquids/{liquid}/comments', 'CommentController@index');
        Route::post('liquids/{liquid}/comments', 'CommentController@store');
        Route::delete('liquids/{liquid}/comments/{comment}', 'CommentController@destroy');

        Route::resource('vendors', 'VendorController', [
            'only' => ['index', 'show']
        ]);

        Route::post('share/{liquid}', 'ShareController@store')->middleware('can:share-liquid,liquid');
        Route::delete('share/{liquid}', 'ShareController@destroy')->middleware('can:unshare-liquid,liquid');
    });

    Route::group([
        'namespace' => 'Admin',
        'middleware' => 'requires-admin',
        'prefix' => 'admin'
    ], function () {
        Route::name('admin.')->group(function () {
            Route::get('', function () {
                return view('admin.index');
            })->name('index');

            Route::resource('vendors', 'VendorController');
            Route::resource('flavours', 'FlavourController');
            Route::resource('users', 'UserController');

            Route::post('flavours/merge', 'FlavourController@merge')->name('flavours.merge');

            Route::get('statistics/flavours', 'StatisticsController@flavourStats')
                ->name('stats.flavours');
            Route::get('statistics/liquids-per-day', 'StatisticsController@liquidsPerDay')
                ->name('stats.liquids-per-day');
        });
    });
});

Route::get('share/{liquid}', 'ShareController@get');

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

if (config('app.registration_enabled')) {
    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');
}

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Flavour.php
<?php

namespace App;

class Flavour extends BaseModel
{
    protected $table = "flavours";
    protected $with = ["vendor"];

    public function author()
    {
        return $this->belongsTo(User::class, 'author_id');
    }

    public function liquids()
    {
        return $this->belongsToMany(Liquid::class)->withPivot('percent');
    }

    public function vendor()
    {
        return $this->belongsTo(Vendor::class);
    }

    public function toArray()
    {
        $data = parent::toArray();
        $data['vendor'] = $this->vendor;
        $data['percent'] = $this->base_percent;

        return $data;
    }
}

app/Http/Controllers/Admin/FlavourController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Flavour;
use App\Services\FlavourService;
use App\Vendor;
use function foo\func;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class FlavourController extends Controller
{
    private $flavourService;

    public function __construct(FlavourService $flavourService)
    {
        $this->flavourService = $flavourService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $flavours = Flavour::all()->map(function ($item) {
            $item->href = route('admin.flavours.edit', $item->id);
            return $item;
        });

        return view('admin.flavours.index', [
            'items' => $flavours
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vendors = Vendor::all()->map(function ($v) {
            return [
                'value' => $v->id,
                'label' => $v->name
            ];
        })->toArray();
        $flavour = new Flavour();

        return view('admin.flavours.create', [
            'flavour' => $flavour,
            'vendors' => $vendors
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'name' => 'required',
            'vendor_id' => 'nullable|exists:vendors,id',
            'is_vg' => 'required|boolean'
        ]);

        $flavour = $this->flavourService->create($data);

        session()->flash('message:success', 'Flavour created');
        return redirect(route('admin.flavours.edit', $flavour->id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Flavour  $flavour
     * @return \Illuminate\Http\Response
     */
    public function edit(Flavour $flavour)
    {
        $vendors = Vendor::all()->map(function ($v) {
            return [
                'label' => $v->name,
                'value' => $v->id
            ];
        })->toArray();

        $flavours = Flavour::where('id', '!=', $flavour->id)->orderBy('name', 'asc')->get()->map(function ($f) {
            $name = $f->name;

            if ($f->vendor) {
                $name .= ' (' . $f->vendor->abbr . ')';
            }
            return [
                'label' => $name,
                'value' => $f->id
            ];
        })->toArray();

        return view('admin.flavours.edit', [
            'flavour' => $flavour,
            'flavours' => $flavours,
            'vendors' => $vendors
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Flavour  $flavour
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Flavour $flavour)
    {
        $data = $this->validate($request, [
            'name' => 'required',
            'vendor_id' => 'nullable|exists:vendors,id',
            'is_vg' => 'required|boolean'
        ]);

        $flavour = $this->flavourService->update($flavour, $data);

        session()->flash('message:success', 'Flavour updated');
        return redirect(route('admin.flavours.edit', $flavour->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Flavour  $flavour
     * @return \Illuminate\Http\Response
     */
    public function destroy(Flavour $flavour)
    {
        $flavour->delete();

        session()->flash('message:success', 'Flavour deleted');
        return redirect(route('admin.flavours.index'));
    }

    public function merge(Request $request)
    {
        $data = $this->validate($request, [
            'from' => 'required|exists:flavours,id',
            'to' => 'required|exists:flavours,id'
        ]);

        $from = Flavour::find($data['from']);
        $to = Flavour::find($data['to']);

        $result = $this->flavourService->mergeFlavours($from, $to);

        if (!$result) {
            return redirect()->back()->withErrors([
                'error' => 'Failed to merge'
            ])->withInput($data);
        }

        session()->flash('message:success', 'Flavours merged');
        return redirect()->route('admin.flavours.edit', [$to->id]);
    }
}

app/Http/Controllers/FlavourController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\InternalServerErrorException;
use App\Flavour;
use App\Services\FlavourService;
use Illuminate\Http\Request;

class FlavourController extends Controller
{
    private $flavourService;

    public function __construct(FlavourService $flavourService)
    {
        $this->flavourService = $flavourService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(Flavour::orderBy('name', 'asc')->get());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     * @throws InternalServerErrorException
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function store(Request $request)
    {
        $this->authorize('create', Flavour::class);

        $data = $this->validate($request, [
            'name' => 'required|min:2',
            'is_vg' => 'required|boolean',
            'vendor_id' => 'nullable|exists:vendors,id',
        ]);
        $data['author_id'] = auth()->id();

        try {
            $flavour = $this->flavourService->create($data);
        } catch (\Exception $ex) {
            throw new InternalServerErrorException($ex->getMessage());
        }

        return response()->json($flavour);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Flavour $flavour
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Flavour $flavour)
    {
        $this->authorize('view', $flavour);

        return response()->json($flavour);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Flavour $flavour
     *
     * @return \Illuminate\Http\Response
     * @throws InternalServerErrorException
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(Request $request, Flavour $flavour)
    {
        $this->authorize('update', $flavour);

        $data = $this->validate($request, [
            'name' => 'required|min:2',
            'is_vg' => 'required|boolean',
            'vendor_id' => 'required|exists:vendors,id',
        ]);

        try {
            $this->flavourService->update($flavour, $data);
        } catch (\Exception $exception) {
            throw new InternalServerErrorException($exception->getMessage());
        }

        return response()->json($flavour);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Flavour $flavour
     *
     * @return \Illuminate\Http\Response
     * @throws InternalServerErrorException
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Flavour $flavour)
    {
        $this->authorize('delete', $flavour);

        try {
            $flavour->delete();
        } catch (\Exception $ex) {
            throw new InternalServerErrorException($ex->getMessage());
        }

        return response(null, 204);
    }
}

resources/views/admin/flavours/create.blade.php
@extends("layouts.admin")

@section("content")
    <div class="admin-edit-page">
        <div class="div">
            <h1>Create Flavour</h1>

            <form action="{{ route('admin.flavours.store') }}" method="post">
                {{ csrf_field() }}

                @if($errors->any())
                    @include("partials.form.errors", [
                        'errors' => $errors->all()
                    ])
                @endif

                @include("admin.flavours.form", [
                    'flavour' => $flavour,
                    'vendors' => $vendors
                ])

                @include("partials.form.submit", [
                    'text' => 'Create',
                    'class' => 'btn primary'
                ])
            </form>
        </div>
    </div>
@endsection

resources/views/admin/flavours/edit.blade.php
@extends("layouts.admin")

@section("content")
    <div class="admin-edit-page">
        <div>
            <h1>Edit Flavour</h1>

            <form action="{{ route('admin.flavours.update', $flavour->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field("PUT") }}

                @if($errors->any())
                    @include("partials.form.errors", [
                        'errors' => $errors->all()
                    ])
                @endif

                @include("admin.flavours.form", [
                    'flavour' => $flavour,
                    'vendors' => $vendors
                ])

                @include("partials.form.submit", [
                    'text' => 'Update',
                    'class' => 'btn primary'
                ])
            </form>

            <div class="merge-form">
                <h2>Merge</h2>
                <p>Merge this flavour into:</p>
                <form method="post" action="{{ route('admin.flavours.merge') }}">
                    {{ csrf_field() }}
                    <input type="hidden" name="from" value="{{ $flavour->id }}">
                    @include("partials.form.select", [
                        'label' => 'Flavour',
                        'name' => 'to',
                        'options' => $flavours,
                        'value' => old('to'),
                        'default' => 'Select'
                    ])

                    <input type="submit" class="btn primary" value="Merge">
                </form>
            </div>

            <div class="delete-form">
                <h2>Delete</h2>
                <form action="{{ route('admin.flavours.destroy', $flavour->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field("DELETE") }}

                    <input type="submit" class="btn danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/flavours/form.blade.php
@include("partials.form.input", [
    'label' => 'Name',
    'value' => old('name', $flavour->name)
])

@include("partials.form.boolean-checkbox", [
    'label' => 'Is VG?',
    'name' => 'is_vg',
    'value' => old('is_vg', $flavour->is_vg)
])

@include("partials.form.select", [
    'label' => 'Vendor',
    'name' => 'vendor_id',
    'options' => $vendors,
    'value' => old('vendor_id', $flavour->vendor_id),
    'default' => 'Other'
])

resources/views/admin/flavours/index.blade.php
@extends("layouts.admin")

@section("content")
    <div class="index-page">
        <h1>Flavours</h1>

        <a href="{{ route('admin.flavours.create') }}">New Flavour</a>

        <v-datatable id="vue-datatable" :headers="[{name: 'id', label: 'ID'}, {name: 'name', label: 'Name'}, {name: 'vendor.name', label: 'Vendor'}, {name: 'created_at', label: 'Created At'}, {name: 'updated_at', label: 'Updated At'}]" :rows="{{ $items }}"></v-datatable>

{{--        <table id="vue-datatable" :items="{{ $items }}">--}}
{{--            <thead>--}}
{{--            <tr>--}}
{{--                <th @click.prevent="sort('id')">ID</th>--}}
{{--                <th @click.prevent="sort('name')">Name</th>--}}
{{--                <th @click.prevent="sort('vendor')">Vendor</th>--}}
{{--                <th @click.prevent="sort('created_at')">Created at</th>--}}
{{--                <th @click.prevent="sort('updated_at')">Updated at</th>--}}
{{--            </tr>--}}
{{--            </thead>--}}

{{--            <tbody>--}}
{{--            @foreach($items as $item)--}}
{{--                <tr v-for="item in items">--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.flavours.edit', $item->id) }}">{{ $item->id }}</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.flavours.edit', $item->id) }}">{{ $item->name }} ({{ array_get($item, 'vendor.abbr', 'Other') }})</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.flavours.edit', $item->id) }}">{{ array_get($item, 'vendor.name', 'Other') }}</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        {{ $item->created_at }}--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        {{ $item->updated_at }}--}}
{{--                    </td>--}}
{{--                </tr>--}}
{{--            @endforeach--}}
{{--            </tbody>--}}
{{--        </table>--}}
    </div>
@endsection