routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {
    Route::get('', 'AppController@app')->name('app');
    Route::get('archived', 'AppController@archived')->name('app.archived');
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::post('profile', 'ProfileController@update')->name('profile:update');

    Route::group(['prefix' => 'ajax'], function () {
        Route::get('liquids/random-name', 'LiquidController@randomName');

        Route::resource('flavours', 'FlavourController', [
            'only' => ['index', 'show', 'store']
        ]);

        Route::resource('liquids', 'LiquidController', [
            'only' => ['index', 'show', 'store', 'update', 'destroy']
        ]);
        Route::post('liquids/{liquid}/new-version', 'LiquidController@newVersion');
        Route::post('liquids/{liquid}/unarchive', 'LiquidController@unarchive');
        Route::get('archived-liquids', 'LiquidController@archived');

        Route::get('liquids/{liquid}/comments', 'CommentController@index');
        Route::post('liquids/{liquid}/comments', 'CommentController@store');
        Route::delete('liquids/{liquid}/comments/{comment}', 'CommentController@destroy');

        Route::resource('vendors', 'VendorController', [
            'only' => ['index', 'show']
        ]);

        Route::post('share/{liquid}', 'ShareController@store')->middleware('can:share-liquid,liquid');
        Route::delete('share/{liquid}', 'ShareController@destroy')->middleware('can:unshare-liquid,liquid');
    });

    Route::group([
        'namespace' => 'Admin',
        'middleware' => 'requires-admin',
        'prefix' => 'admin'
    ], function () {
        Route::name('admin.')->group(function () {
            Route::get('', function () {
                return view('admin.index');
            })->name('index');

            Route::resource('vendors', 'VendorController');
            Route::resource('flavours', 'FlavourController');
            Route::resource('users', 'UserController');

            Route::post('flavours/merge', 'FlavourController@merge')->name('flavours.merge');

            Route::get('statistics/flavours', 'StatisticsController@flavourStats')
                ->name('stats.flavours');
            Route::get('statistics/liquids-per-day', 'StatisticsController@liquidsPerDay')
                ->name('stats.liquids-per-day');
        });
    });
});

Route::get('share/{liquid}', 'ShareController@get');

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

if (config('app.registration_enabled')) {
    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');
}

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = "users";

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'username', 'email', 'password', 'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Validation\Rule;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.users.index', [
            'items' => User::all()->map(function ($item) {
                $item->href = route('admin.users.edit', $item->id);
                return $item;
            })
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create', [
            'user' => new User()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'username' => 'required|unique:users,username',
            'email' => 'required|unique:users,email',
            'password' => 'required|min:6',
            'role' => 'required'
        ]);

        if (!empty($data['password'])) {
            $data['password'] = bcrypt($data['password']);
        }

        $user = new User($data);
        $user->save();

        return redirect(route('admin.users.edit', $user->id));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', [
            'user' => $user
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $data = $this->validate($request, [
            'username' => [
                'required',
                Rule::unique('users', 'username')
                ->whereNot('id', $user->id)
            ],
            'email' => [
                'required',
                Rule::unique('users', 'email')
                    ->whereNot('id', $user->id)
            ],
            'password' => 'nullable|min:6',
            'role' => 'required'
        ]);

        if (!empty($data['password'])) {
            $data['password'] = bcrypt($data['password']);
        } else {
            unset($data['password']);
        }

        $user->fill($data);
        $user->save();

        return redirect(route('admin.users.edit', $user->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        session()->flash('message:success', 'User deleted');
        return redirect(route('admin.users.index'));
    }
}

resources/views/admin/users/create.blade.php
@extends("layouts.admin")

@section("content")
    <div class="admin-edit-page">
        <div class="div">
            <h1>Create User</h1>

            <form action="{{ route('admin.users.store') }}" method="post">
                {{ csrf_field() }}

                @if($errors->any())
                    @include("partials.form.errors", [
                        'errors' => $errors->all()
                    ])
                @endif

                @include("admin.users.form", [
                    'user' => $user
                ])

                @include("partials.form.submit", [
                    'text' => 'Create',
                    'class' => 'btn primary'
                ])
            </form>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends("layouts.admin")

@section("content")
    <div class="admin-edit-page">
        <div>
            <h1>Edit User</h1>

            <form action="{{ route('admin.users.update', $user->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field("PUT") }}

                @if($errors->any())
                    @include("partials.form.errors", [
                        'errors' => $errors->all()
                    ])
                @endif

                @include("admin.users.form", [
                    'user' => $user
                ])

                @include("partials.form.submit", [
                    'text' => 'Update',
                    'class' => 'btn primary'
                ])
            </form>

            <div class="delete-form">
                <h2>Delete</h2>
                <form action="{{ route('admin.vendors.destroy', $user->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field("DELETE") }}

                    <input type="submit" class="btn danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/form.blade.php
@include("partials.form.input", [
    'label' => 'Username',
    'value' => old('username', $user->username)
])

@include("partials.form.input", [
    'label' => 'Email',
    'type' => 'email',
    'value' => old('email', $user->email)
])

@include("partials.form.input", [
    'label' => 'Password',
    'type' => 'password'
])

@include("partials.form.select", [
    'label' => 'Role',
    'options' => [
        ['label' => 'User', 'value' => 'user'],
        ['label' => 'Admin', 'value' => 'admin']
    ],
    'value' => old('role', $user->role)
])

resources/views/admin/users/index.blade.php
@extends("layouts.admin")

@section("content")
    <div class="index-page">
        <h1>Users</h1>

        <a href="{{ route('admin.users.create') }}">New User</a>

        <v-datatable id="vue-datatable" :headers="[{name: 'id', label: 'ID'}, {name: 'username', label: 'Username'}, {name: 'email', label: 'Email'}, {name: 'created_at', label: 'Created At'}, {name: 'updated_at', label: 'Updated At'}]" :rows="{{ $items }}"></v-datatable>

{{--        <table class="datatable">--}}
{{--            <thead>--}}
{{--            <tr>--}}
{{--                <th>ID</th>--}}
{{--                <th>Username</th>--}}
{{--                <th>Email</th>--}}
{{--                <th>Created at</th>--}}
{{--                <th>Updated at</th>--}}
{{--            </tr>--}}
{{--            </thead>--}}

{{--            <tbody>--}}
{{--            @foreach($items as $item)--}}
{{--                <tr>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.users.edit', $item->id) }}">{{ $item->id }}</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.users.edit', $item->id) }}">{{ $item->username }}</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.users.edit', $item->id) }}">{{ $item->email}}</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        {{ $item->created_at }}--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        {{ $item->updated_at }}--}}
{{--                    </td>--}}
{{--                </tr>--}}
{{--            @endforeach--}}
{{--            </tbody>--}}
{{--        </table>--}}
    </div>
@endsection