routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth'], function () {
    Route::get('', 'AppController@app')->name('app');
    Route::get('archived', 'AppController@archived')->name('app.archived');
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::post('profile', 'ProfileController@update')->name('profile:update');

    Route::group(['prefix' => 'ajax'], function () {
        Route::get('liquids/random-name', 'LiquidController@randomName');

        Route::resource('flavours', 'FlavourController', [
            'only' => ['index', 'show', 'store']
        ]);

        Route::resource('liquids', 'LiquidController', [
            'only' => ['index', 'show', 'store', 'update', 'destroy']
        ]);
        Route::post('liquids/{liquid}/new-version', 'LiquidController@newVersion');
        Route::post('liquids/{liquid}/unarchive', 'LiquidController@unarchive');
        Route::get('archived-liquids', 'LiquidController@archived');

        Route::get('liquids/{liquid}/comments', 'CommentController@index');
        Route::post('liquids/{liquid}/comments', 'CommentController@store');
        Route::delete('liquids/{liquid}/comments/{comment}', 'CommentController@destroy');

        Route::resource('vendors', 'VendorController', [
            'only' => ['index', 'show']
        ]);

        Route::post('share/{liquid}', 'ShareController@store')->middleware('can:share-liquid,liquid');
        Route::delete('share/{liquid}', 'ShareController@destroy')->middleware('can:unshare-liquid,liquid');
    });

    Route::group([
        'namespace' => 'Admin',
        'middleware' => 'requires-admin',
        'prefix' => 'admin'
    ], function () {
        Route::name('admin.')->group(function () {
            Route::get('', function () {
                return view('admin.index');
            })->name('index');

            Route::resource('vendors', 'VendorController');
            Route::resource('flavours', 'FlavourController');
            Route::resource('users', 'UserController');

            Route::post('flavours/merge', 'FlavourController@merge')->name('flavours.merge');

            Route::get('statistics/flavours', 'StatisticsController@flavourStats')
                ->name('stats.flavours');
            Route::get('statistics/liquids-per-day', 'StatisticsController@liquidsPerDay')
                ->name('stats.liquids-per-day');
        });
    });
});

Route::get('share/{liquid}', 'ShareController@get');

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

if (config('app.registration_enabled')) {
    // Registration Routes...
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');
}

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset');

app/Vendor.php
<?php
namespace App;

class Vendor extends BaseModel
{
    protected $table = "vendors";
}

app/Http/Controllers/Admin/VendorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Services\VendorService;
use App\Vendor;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class VendorController extends Controller
{
    private $vendorService;

    public function __construct(VendorService $vendorService)
    {
        $this->vendorService = $vendorService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $vendors = Vendor::all()->map(function ($item) {
            $item->href = route('admin.vendors.edit', $item->id);
            return $item;
        });

        return view('admin.vendors.index', [
            'items' => $vendors
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $vendor = new Vendor();

        return view('admin.vendors.create', [
            'vendor' => $vendor
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'name' => 'required',
            'abbr' => 'nullable'
        ]);

        $data['author_id'] = auth()->id();

        $vendor = $this->vendorService->create($data);

        session()->flash('message:success', 'Vendor created');
        return redirect(route('admin.vendors.edit', $vendor->id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function edit(Vendor $vendor)
    {
        return view('admin.vendors.edit', [
            'vendor' => $vendor
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vendor $vendor)
    {
        $data = $this->validate($request, [
            'name' => 'required',
            'abbr' => 'nullable'
        ]);

        $data['author_id'] = auth()->id();

        $vendor = $this->vendorService->update($vendor, $data);

        session()->flash('message:success', 'Vendor updated');
        return redirect(route('admin.vendors.edit', $vendor->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Vendor  $vendor
     * @return \Illuminate\Http\Response
     */
    public function destroy(Vendor $vendor)
    {
        $vendor->delete();

        session()->flash('message:success', 'Vendor deleted');
        return redirect(route('admin.vendors.index'));
    }
}

app/Http/Controllers/VendorController.php
<?php

namespace App\Http\Controllers;

use App\Exceptions\InternalServerErrorException;
use App\Services\VendorService;
use App\Vendor;
use Illuminate\Http\Request;

class VendorController extends Controller
{
    /**
     * @var VendorService
     */
    private $vendorService;

    public function __construct(VendorService $vendorService)
    {
        $this->vendorService = $vendorService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return response()->json(Vendor::all());
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Vendor $vendor
     *
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(Vendor $vendor)
    {
        $this->authorize('view', $vendor);
        return response()->json($vendor);
    }
}

resources/views/admin/vendors/create.blade.php
@extends("layouts.admin")

@section("content")
    <div class="admin-edit-page">
        <div class="div">
            <h1>Create Vendor</h1>

            <form action="{{ route('admin.vendors.store') }}" method="post">
                {{ csrf_field() }}

                @if($errors->any())
                    @include("partials.form.errors", [
                        'errors' => $errors->all()
                    ])
                @endif

                @include("admin.vendors.form", [
                    "vendor" => $vendor
                ])

                @include("partials.form.submit", [
                    'text' => 'Create',
                    'class' => 'btn primary'
                ])
            </form>
        </div>
    </div>
@endsection

resources/views/admin/vendors/edit.blade.php
@extends("layouts.admin")

@section("content")
    <div class="admin-edit-page">
        <div>
            <h1>Edit Vendor</h1>

            <form action="{{ route('admin.vendors.update', $vendor->id) }}" method="post">
                {{ csrf_field() }}
                {{ method_field('PUT') }}
                @if($errors->any())
                    @include("partials.form.errors", [
                        'errors' => $errors->all()
                    ])
                @endif

                @include("admin.vendors.form", [
                    "vendor" => $vendor
                ])

                @include("partials.form.submit", [
                    'text' => 'Update',
                    'class' => 'btn primary'
                ])
            </form>

            <div class="delete-form">
                <h2>Delete</h2>
                <form action="{{ route('admin.vendors.destroy', $vendor->id) }}" method="post">
                    {{ csrf_field() }}
                    {{ method_field("DELETE") }}

                    <input type="submit" class="btn danger" value="Delete">
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/vendors/form.blade.php
@include("partials.form.input", [
    'label' => 'Name',
    'value' => old('name', $vendor->name)
])

@include("partials.form.input", [
    'label' => 'Abbreviation',
    'name' => 'abbr',
    'value' => old('abbr', $vendor->abbr)
])

resources/views/admin/vendors/index.blade.php
@extends("layouts.admin")

@section("content")
    <div class="index-page">
        <h1>Vendors</h1>

        <a href="{{ route('admin.vendors.create') }}">New Vendor</a>

        <v-datatable id="vue-datatable" :headers="[{name: 'id', label: 'ID'}, {name: 'name', label: 'Name'}, {name: 'abbr', label: 'Abbreviation'}, {name: 'created_at', label: 'Created At'}, {name: 'updated_at', label: 'Updated At'}]" :rows="{{ $items }}"></v-datatable>

{{--        <table class="datatable">--}}
{{--            <thead>--}}
{{--            <tr>--}}
{{--                <th>ID</th>--}}
{{--                <th>Name</th>--}}
{{--                <th>Abbreviation</th>--}}
{{--                <th>Created at</th>--}}
{{--                <th>Updated at</th>--}}
{{--            </tr>--}}
{{--            </thead>--}}

{{--            <tbody>--}}
{{--            @foreach($items as $item)--}}
{{--                <tr>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.vendors.edit', $item->id) }}">{{ $item->id }}</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.vendors.edit', $item->id) }}">{{ $item->name }}</a>--}}
{{--                    </td>--}}
{{--                    <td>--}}
{{--                        <a href="{{ route('admin.vendors.edit', $item->id) }}">{{ $item->abbr }}</a>--}}
{{--                    </td>--}}
{{--                    <td>{{ $item->created_at }}</td>--}}
{{--                    <td>{{ $item->updated_at }}</td>--}}
{{--                </tr>--}}
{{--            @endforeach--}}
{{--            </tbody>--}}
{{--        </table>--}}
    </div>
@endsection